version: '3.5'
services:
    react-site:
        container_name: react-site
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - .:/app
        ports:
            - '3000:3000'
        networks:
            - default
